version: '3'

services:

  back1:
    build:
      context: ../..
      dockerfile: ../../Dockerfile
    ports:
      - "8080:8080"

  back2:
    build:
      context: ../..
      dockerfile: ../../Dockerfile
    ports:
      - "8081:8080"
